In [18]:
import torch
import torchvision
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

In [19]:
class WineDataset(Dataset):
    def __init__(self) -> None:
        xy      = np.loadtxt('dataset/wine.csv', delimiter=",", dtype=np.float32, skiprows=1)
        self.x  = torch.from_numpy(xy[:, 1: ])
        self.y  = torch.from_numpy(xy[:, [0]])
        self.n_samples = xy.shape[0]
        self.n_feature = self.x.shape[1]
    
    def __getitem__(self, index):
        return self.x[index], self.y[index]
    
    def __len__(self):
        return self.n_samples

dataset = WineDataset()
dataloader = DataLoader(dataset=dataset, batch_size=4, shuffle=True)

In [20]:
first_data = dataset[0]
features, label = first_data
print(features)
print(label)

dataiter = iter(dataloader)
data = dataiter._next_data()
features, label = data
print(features)
print(label)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03])
tensor([1.])
tensor([[1.3160e+01, 3.5700e+00, 2.1500e+00, 2.1000e+01, 1.0200e+02, 1.5000e+00,
         5.5000e-01, 4.3000e-01, 1.3000e+00, 4.0000e+00, 6.0000e-01, 1.6800e+00,
         8.3000e+02],
        [1.3280e+01, 1.6400e+00, 2.8400e+00, 1.5500e+01, 1.1000e+02, 2.6000e+00,
         2.6800e+00, 3.4000e-01, 1.3600e+00, 4.6000e+00, 1.0900e+00, 2.7800e+00,
         8.8000e+02],
        [1.2370e+01, 1.2100e+00, 2.5600e+00, 1.8100e+01, 9.8000e+01, 2.4200e+00,
         2.6500e+00, 3.7000e-01, 2.0800e+00, 4.6000e+00, 1.1900e+00, 2.3000e+00,
         6.7800e+02],
        [1.4210e+01, 4.0400e+00, 2.4400e+00, 1.8900e+01, 1.1100e+02, 2.8500e+00,
         2.6500e+00, 3.0000e-01, 1.2500e+00, 5.2400e+00, 8.7000e-01, 3.3300e+00,
         1.0800e+03]])
tensor([[3.],
        [1.],
        [2.],
        [1.]])


In [21]:
num_epochs = 2
total_samples = len(dataset)
n_iteration = math.ceil(total_samples / 4) 

for epoch in range(num_epochs):
    for i, (input, labels) in enumerate(dataloader):
        # forward, backward and update
        ...