In [22]:
import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

In [23]:
class WineDataset(Dataset):
    def __init__(self) -> None:
        xy      = np.loadtxt('dataset/wine.csv', delimiter=",", dtype=np.float32, skiprows=1)
        self.x  = torch.from_numpy(xy[:, 1: ])
        self.y  = torch.from_numpy(xy[:, [0]])
        self.n_samples = xy.shape[0]
        self.n_feature = self.x.shape[1]
    
    def __getitem__(self, index):
        return self.x[index], self.y[index]
    
    def __len__(self):
        return self.n_samples

dataset = WineDataset()
dataloader = DataLoader(dataset=dataset, batch_size=4, shuffle=True)

In [24]:
first_data = dataset[0]
features, label = first_data
print(features)
print(label)

dataiter = iter(dataloader)
data = dataiter._next_data()
features, label = data
print(features)
print(label)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03])
tensor([1.])
tensor([[1.3580e+01, 1.6600e+00, 2.3600e+00, 1.9100e+01, 1.0600e+02, 2.8600e+00,
         3.1900e+00, 2.2000e-01, 1.9500e+00, 6.9000e+00, 1.0900e+00, 2.8800e+00,
         1.5150e+03],
        [1.1840e+01, 8.9000e-01, 2.5800e+00, 1.8000e+01, 9.4000e+01, 2.2000e+00,
         2.2100e+00, 2.2000e-01, 2.3500e+00, 3.0500e+00, 7.9000e-01, 3.0800e+00,
         5.2000e+02],
        [1.3870e+01, 1.9000e+00, 2.8000e+00, 1.9400e+01, 1.0700e+02, 2.9500e+00,
         2.9700e+00, 3.7000e-01, 1.7600e+00, 4.5000e+00, 1.2500e+00, 3.4000e+00,
         9.1500e+02],
        [1.3170e+01, 2.5900e+00, 2.3700e+00, 2.0000e+01, 1.2000e+02, 1.6500e+00,
         6.8000e-01, 5.3000e-01, 1.4600e+00, 9.3000e+00, 6.0000e-01, 1.6200e+00,
         8.4000e+02]])
tensor([[1.],
        [2.],
        [1.],
        [3.]])


In [25]:
num_epochs = 2
total_samples = len(dataset)
n_iteration = math.ceil(total_samples / 4) 

for epoch in range(num_epochs):
    for i, (input, labels) in enumerate(dataloader):
        # forward, backward and update
        ...